### ISSUE TITLE
IE11 Compatability

### ISSUE THREAD

**Issue by zslabs** [jshjohnson/Choices#27]
Hi,
Using IE11 (with an addition of https://cdn.polyfill.io/v2/polyfill.min.js?features=default,matchMedia,fetch,Element.prototype.placeholder,Array.prototype.includes to hopefully grab everything I'd need to for compatibility since I was seeing `fetch` used) the UI isn't responding correctly; selections are not being added to the list of options; they just disappear. Are there any additional deps I should be using to solidify the browser support?

**Comment by jshjohnson** [comment]
Hi @zslabs;

Would you be able to send me your config for Choices so I can try and identify the issue?

Thanks

**Comment by zslabs** [comment]
Hey!
I was testing the default GH pages build (locally) under VirtualBox's modernIE build of IE11.

**Comment by jshjohnson** [comment]
Hi @zslabs,

This has been resolved as of version 1.1.3. IE doesn't support DocumentFragment.children so I've opted for DocumentFragment.childNodes instead.

Thanks

**Comment by zslabs** [comment]
Awesome! Thanks so much for jumping on that; can confirm it's working as expected. Appreciate it!

**Comment by rstacruz** [comment]
I think we still have some IE11 issues. Searching doesn't seem to work. I'll update if I can make a replicable test case.

**Comment by inergy** [comment]
I'm seeing issues with ie11, due to the unsupported es2015 code in the index file:

> SCRIPT1002: Syntax error
> Choices (249,31)

`
249        addItemText: (value) => {
250          return `Appuyez sur Entrée pour ajouter <b>"${value}"</b>`;
251        },
`

**Comment by jshjohnson** [comment]
Hi @inergy,

Is this on the demo site or your own code?

Thans

**Comment by inergy** [comment]
On the demo site and I've cloned the repo and can reproduce locally.  The index.html file has es2015 code, which I tracked it down to [this commit].(https://github.com/jshjohnson/Choices/commit/8be12c20cd514febd6d0a79c73988129c2f9c5ea#diff-eacf331f0ffc35d4b482f1d15a887d3b)

I did a quick refactor using es5 and things started working as expected (although, there are a few issues to be resolve after fixing the arrow functions and template literals).

**Comment by jshjohnson** [comment]
Thanks for the heads up - this should now be resolved with these two commits:

- https://github.com/jshjohnson/Choices/commit/31a57a0e2b42a611e74cac4fd70c2b10163c15ad
- https://github.com/jshjohnson/Choices/commit/9bb84df8d0466c79c75c332b09d4dc6efc1a8472

👍
