### ISSUE TITLE
Is the any way to use this plugin without webpack?

### ISSUE THREAD

**Issue by carlotrimarchi** [jshjohnson/Choices#287]
Hello,
I downloaded the dist version of the plugin and when I try to use it I get this error:

`TypeError: "exports" is read-only`

I might be wrong, but I'm guessing it's because I'm not using webpack or anything else that can manage Javascript modules.
I simply use gulp to minimize e transpile the javascript code, but that's it.

Is there any way to use this script without webpack?

**Comment by fernandoagarcia** [comment]
You can download the source and change this to window on the first IIFE call. You should be able to combine it with your other JS files.

**Comment by jshjohnson** [comment]
You shouldn’t need to do that - when it builds webpack should export to window (using the UMD definition). This sounds more like an issue with that

**Comment by jshjohnson** [comment]
This should be resolved by this commit: https://github.com/jshjohnson/Choices/commit/e8d8f8662ec78457a4b35d039818e62a7eab18bf

**Comment by carlotrimarchi** [comment]
@jshjohnson it still doesn't work for me. Simply including it in the page I get this error in the console:

```
 Uncaught TypeError: Cannot set property 'Choices' of undefined
    at choices.js:10
    at choices.js:2
```

**Comment by jshjohnson** [comment]
I just tried to replicate your problem and couldn't. If you pull master and open index.html in a browser, you should see working examples.
